name: 02 - Build and Push Docker Image

on:
  workflow_run:
    workflows: ["00 - PR check"]
    types:
      - completed
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag epampavelklindziuk/sas-pipeline:tagname:0.0.1-SNAPSHOT
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Docker Push
        run: docker push 'epampavelklindziuk/sas-pipeline:tagname:0.0.1-SNAPSHOT'