name: 03 - Deploy PROD and Smoke Test

on:
  workflow_run:
    workflows: ["02 - Deploy LT and Performance Test"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-heroku-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: "epl-players"
          healthcheck: "https://epl-players.herokuapp.com/health"
  smoke-test:
    if: ${{ success() }}
    needs: deploy-to-heroku-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run integration tests
        run: ./gradlew smokeTest -i
